from matplotlib import pyplot as plt
import numpy as np
def distance(x, y):
    print(f'Евклидово расстояние между  {x}, {y}:', np.linalg.norm(x - y))
    print(f'Квадрат Евклидова расстояния между {x}, {y}:', np.linalg.norm(x - y) ** 2)
    print(f'Растояние Чебышева между  {x}, {y}:', np.linalg.norm(x - y, ord=np.inf))
    print(f'Расстяние Хемминга между {x}, {y}:', np.linalg.norm(x - y, ord=1))
a = np.array([0, 0, 0])
b = np.array([0, 0, 1])
c = np.array([1, 0, 1])
d = np.array([1, 1, 1])
distance(a,b)
distance(a,c)
distance(a,d)
distance(b,c)
distance(b,d)
distance(c,d)
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(*a)
ax.scatter(*b)
ax.scatter(*c)
ax.scatter(*d)
plt.show()